### ISSUE TITLE
 can't execute file: /root/blog/bin/renderServer.js

### ISSUE THREAD

**Issue by Vbubblery** [mhbseal/blog#10]
npm -v ->3.9.5
node -v -> v6.2.2

```
[piping] can't execute file: /root/blog/bin/renderServer.js
[piping] error given was: Error: imports[1] for react-transform-catch-errors does not look like a React component.
    at catchErrors (/root/blog/node_modules/react-transform-catch-errors/lib/index.js:26:11)
    at Object.<anonymous> (/root/blog/fe/src/helpers/Html.js:4:47)
    at Module._compile (module.js:541:32)
    at normalLoader (/root/blog/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/blog/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Module._load (module.js:409:3)
    at Function.module._load (/root/blog/node_modules/piping/lib/launcher.js:32:16)
    at Module.require (module.js:468:17)
[piping] further repeats of this error will be suppressed...
Hash: 88ce4cd8fb0aa6194a55
Version: webpack 1.13.1
Time: 24863ms

```

**Comment by mhbseal** [comment]
@Vbubblery 这种问题一般都是pkg的依赖版本的问题，看这里 http://stackoverflow.com/questions/37895944/react-transform-catch-errors-does-not-look-like-a-react-component
