### ISSUE TITLE
跑不起来，报错

### ISSUE THREAD

**Issue by younth** [mhbseal/blog#2]
```
[piping] can't execute file: /Users/baidu/source/react/blog/bin/renderServer.js
[piping] error given was: Error: Cannot find module 'invariant'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function._module3.default._resolveFilename (/Users/baidu/source/react/blog/node_modules/webpack-isomorphic-tools/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:403:34)
    at Function.module._load (/Users/baidu/source/react/blog/node_modules/piping/lib/launcher.js:24:23)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

```

**Comment by younth** [comment]
node ./bin/renderServer  这个报的错

**Comment by mhbseal** [comment]
@younth 看报错，Error: Cannot find module 'invariant'，install一下invariant这个pkg！

**Comment by younth** [comment]
多谢，已解决~感觉npm包有点老了，我把相关的升级到最新就好使了。。
